// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.Wordpress":       schema_pkg_apis_wordpress_v1alpha1_Wordpress(ref),
		"github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.WordpressSpec":   schema_pkg_apis_wordpress_v1alpha1_WordpressSpec(ref),
		"github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.WordpressStatus": schema_pkg_apis_wordpress_v1alpha1_WordpressStatus(ref),
	}
}

func schema_pkg_apis_wordpress_v1alpha1_Wordpress(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Wordpress is the Schema for the wordpresses API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.WordpressSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.WordpressStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.WordpressSpec", "github.com/autimo/wordpress-operator/pkg/apis/wordpress/v1alpha1.WordpressStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_wordpress_v1alpha1_WordpressSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WordpressSpec defines the desired state of Wordpress",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_wordpress_v1alpha1_WordpressStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WordpressStatus defines the observed state of Wordpress",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
